/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Admin
 */
public class ReportsPanel extends javax.swing.JPanel {
//    GridBagLayout layout1 = new GridBagLayout();
//        Old1 o1 = new Old1();
//        Old2 o2 = new Old2();
//        Old3 o3 = new Old3();
//        New1 n1 = new New1();
//        New2 n2 = new New2();
//        New3 n3 = new New3();
    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel() {
      
     
        initComponents();
        

//        pView.setLayout(layout1);
//        GridBagConstraints c = new GridBagConstraints();
//        c.gridx = 0;
//        c.gridx = 0;
//        pView.add(o1, c);
//        c.gridx = 0;
//        c.gridx = 0;
//        pView.add(o2, c);
//        c.gridx = 0;
//        c.gridx = 0;
//        pView.add(o3, c);
//        c.gridx = 0;
//        c.gridx = 0;
//        pView.add(n1, c);
//        c.gridx = 0;
//        c.gridx = 0;
//        pView.add(n2, c);
//        c.gridx = 0;
//        c.gridx = 0;
//        pView.add(n3, c);
//        o1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnold1 = new javax.swing.JButton();
        btnold2 = new javax.swing.JButton();
        btnold3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnnew1 = new javax.swing.JButton();
        btnnew2 = new javax.swing.JButton();
        btnnew3 = new javax.swing.JButton();
        pView = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(999, 675));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Báo Cáo Tăng Trưởng Doanh Thu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        btnold1.setText("Quý I");
        btnold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnold1ActionPerformed(evt);
            }
        });

        btnold2.setText("Quý II");
        btnold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnold2ActionPerformed(evt);
            }
        });

        btnold3.setText("Quý III");
        btnold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnold3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("This Year's Plan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Plan for the future");

        btnnew1.setText("Quý I");
        btnnew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnew1ActionPerformed(evt);
            }
        });

        btnnew2.setForeground(new java.awt.Color(0, 0, 0));
        btnnew2.setText("Quý II");
        btnnew2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnew2ActionPerformed(evt);
            }
        });

        btnnew3.setText("Quý III");
        btnnew3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnew3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnold1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnold2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnold3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(btnnew1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnnew2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnnew3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnold1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnold2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnold3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnew1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnnew2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnnew3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pViewLayout = new javax.swing.GroupLayout(pView);
        pView.setLayout(pViewLayout);
        pViewLayout.setHorizontalGroup(
            pViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pViewLayout.setVerticalGroup(
            pViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnold1ActionPerformed
//        o1.setVisible(true);
//        o2.setVisible(false);
//        o3.setVisible(false);
//        n1.setVisible(false);
//        n2.setVisible(false);
//        n3.setVisible(false);
        
    }//GEN-LAST:event_btnold1ActionPerformed

    private void btnold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnold2ActionPerformed
//        o1.setVisible(false);
//        o2.setVisible(true);
//        o3.setVisible(false);
//        n1.setVisible(false);
//        n2.setVisible(false);
//        n3.setVisible(false);
    }//GEN-LAST:event_btnold2ActionPerformed

    private void btnold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnold3ActionPerformed
//       o1.setVisible(false);
//        o2.setVisible(false);
//        o3.setVisible(true);
//        n1.setVisible(false);
//        n2.setVisible(false);
//        n3.setVisible(false);
    }//GEN-LAST:event_btnold3ActionPerformed

    private void btnnew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnew1ActionPerformed
//        o1.setVisible(false);
//        o2.setVisible(false);
//        o3.setVisible(false);
//        n1.setVisible(true);
//        n2.setVisible(false);
//        n3.setVisible(false);
    }//GEN-LAST:event_btnnew1ActionPerformed

    private void btnnew2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnew2ActionPerformed
//        o1.setVisible(false);
//        o2.setVisible(false);
//        o3.setVisible(false);
//        n1.setVisible(false);
//        n2.setVisible(true);
//        n3.setVisible(false);
    }//GEN-LAST:event_btnnew2ActionPerformed

    private void btnnew3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnew3ActionPerformed
//        o1.setVisible(false);
//        o2.setVisible(false);
//        o3.setVisible(false);
//        n1.setVisible(false);
//        n2.setVisible(false);
//        n3.setVisible(true);
    }//GEN-LAST:event_btnnew3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnew1;
    private javax.swing.JButton btnnew2;
    private javax.swing.JButton btnnew3;
    private javax.swing.JButton btnold1;
    private javax.swing.JButton btnold2;
    private javax.swing.JButton btnold3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pView;
    // End of variables declaration//GEN-END:variables
}
